#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG SENSOR HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

template<typename Config>
inline bool migrate_saved_config_sensor_legacy(Config &config) {
  if (config.type == "local_sensor") {
    config.type = "sensor";
    config.sensor = "local";
    config.icon_on = "Auto";
    config.options = "";
    return true;
  }
  return false;
}
