#pragma once

// =============================================================================
// GENERATED SAVED-CONFIG PRODUCTION OPTION HELPERS - do not edit by hand
// Generated by scripts/build.py from common/config/card_contract.json.
// =============================================================================

#include <string>

inline std::string normalize_saved_config_vacuum_options(const std::string &) {
  return "";
}
