// =============================================================================
// GENERATED FIRMWARE I18N - do not edit by hand
// Generated by scripts/build.py from common/config/strings.*.txt.
// =============================================================================
#pragma once
#include <cstring>
#include <string>

inline std::string &espcontrol_language_code() {
  static std::string language = "en";
  return language;
}

inline void set_espcontrol_language(const std::string &language) {
  espcontrol_language_code() = language;
}

inline const char *espcontrol_i18n_it(const char *text) {
  if (!text) return "";
  if (std::strcmp(text, "(untitled)") == 0) return "(senza titolo)";
  if (std::strcmp(text, "Action") == 0) return "Azione";
  if (std::strcmp(text, "Alarm") == 0) return "Allarme";
  if (std::strcmp(text, "Alarm action failed") == 0) return "Azione allarme non riuscita";
  if (std::strcmp(text, "Alarm did not change") == 0) return "Allarme invariato";
  if (std::strcmp(text, "All done") == 0) return "Completato";
  if (std::strcmp(text, "Always On") == 0) return "Sempre acceso";
  if (std::strcmp(text, "Arm Away") == 0) return "Inserisci fuori casa";
  if (std::strcmp(text, "Arm Home") == 0) return "Inserisci in casa";
  if (std::strcmp(text, "Armed Away") == 0) return "Inserito fuori casa";
  if (std::strcmp(text, "Armed Custom") == 0) return "Inserito personalizzato";
  if (std::strcmp(text, "Armed Home") == 0) return "Inserito in casa";
  if (std::strcmp(text, "Armed Night") == 0) return "Inserito notte";
  if (std::strcmp(text, "Arming") == 0) return "Inserimento";
  if (std::strcmp(text, "Away") == 0) return "Fuori casa";
  if (std::strcmp(text, "Back") == 0) return "Indietro";
  if (std::strcmp(text, "Clear Night") == 0) return "Notte serena";
  if (std::strcmp(text, "Climate") == 0) return "Clima";
  if (std::strcmp(text, "Clock") == 0) return "Orologio";
  if (std::strcmp(text, "Close") == 0) return "Chiudi";
  if (std::strcmp(text, "Cloudy") == 0) return "Nuvoloso";
  if (std::strcmp(text, "Cloudy Alert") == 0) return "Allerta nuvole";
  if (std::strcmp(text, "Configure") == 0) return "Configura";
  if (std::strcmp(text, "Cool") == 0) return "Freddo";
  if (std::strcmp(text, "Cooling") == 0) return "Raffreddamento";
  if (std::strcmp(text, "Could not complete") == 0) return "Impossibile completare";
  if (std::strcmp(text, "Could not load") == 0) return "Impossibile caricare";
  if (std::strcmp(text, "Cover") == 0) return "Tapparella";
  if (std::strcmp(text, "Date") == 0) return "Data";
  if (std::strcmp(text, "Dev build") == 0) return "Build dev";
  if (std::strcmp(text, "Dimmed") == 0) return "Attenuato";
  if (std::strcmp(text, "Direction") == 0) return "Direzione";
  if (std::strcmp(text, "Disarm") == 0) return "Disinserisci";
  if (std::strcmp(text, "Disarmed") == 0) return "Disinserito";
  if (std::strcmp(text, "Door") == 0) return "Porta";
  if (std::strcmp(text, "Door Open") == 0) return "Porta aperta";
  if (std::strcmp(text, "Dry") == 0) return "Deumidifica";
  if (std::strcmp(text, "Drying") == 0) return "Deumidificazione";
  if (std::strcmp(text, "Dust") == 0) return "Polvere";
  if (std::strcmp(text, "Enter Pin") == 0) return "Inserisci PIN";
  if (std::strcmp(text, "Exceptional") == 0) return "Eccezionale";
  if (std::strcmp(text, "Fan") == 0) return "Ventola";
  if (std::strcmp(text, "Fog") == 0) return "Nebbia";
  if (std::strcmp(text, "Garage Door") == 0) return "Porta garage";
  if (std::strcmp(text, "Hail") == 0) return "Grandine";
  if (std::strcmp(text, "Hazy") == 0) return "Foschia";
  if (std::strcmp(text, "Heat") == 0) return "Caldo";
  if (std::strcmp(text, "Heat/Cool") == 0) return "Caldo/Freddo";
  if (std::strcmp(text, "Heating") == 0) return "Riscaldamento";
  if (std::strcmp(text, "Heavy Snow") == 0) return "Neve intensa";
  if (std::strcmp(text, "High") == 0) return "Alto";
  if (std::strcmp(text, "High target") == 0) return "Target alto";
  if (std::strcmp(text, "Home") == 0) return "Casa";
  if (std::strcmp(text, "Hourly") == 0) return "Ogni ora";
  if (std::strcmp(text, "Hurricane") == 0) return "Uragano";
  if (std::strcmp(text, "Idle") == 0) return "Inattivo";
  if (std::strcmp(text, "Lightning") == 0) return "Fulmini";
  if (std::strcmp(text, "Lightning And Rain") == 0) return "Fulmini e pioggia";
  if (std::strcmp(text, "Loading") == 0) return "Caricamento";
  if (std::strcmp(text, "Lock") == 0) return "Blocca";
  if (std::strcmp(text, "Low") == 0) return "Basso";
  if (std::strcmp(text, "Low target") == 0) return "Target basso";
  if (std::strcmp(text, "Mode") == 0) return "Modalità";
  if (std::strcmp(text, "Monthly") == 0) return "Mensile";
  if (std::strcmp(text, "Next") == 0) return "Avanti";
  if (std::strcmp(text, "None") == 0) return "Nessuno";
  if (std::strcmp(text, "No options") == 0) return "Nessuna opzione";
  if (std::strcmp(text, "No presets") == 0) return "Nessun preset";
  if (std::strcmp(text, "Not available") == 0) return "Non disponibile";
  if (std::strcmp(text, "Off") == 0) return "Spento";
  if (std::strcmp(text, "On") == 0) return "Acceso";
  if (std::strcmp(text, "Open") == 0) return "Apri";
  if (std::strcmp(text, "Option") == 0) return "Opzione";
  if (std::strcmp(text, "Oscillating") == 0) return "Oscillante";
  if (std::strcmp(text, "Oscillation") == 0) return "Oscillazione";
  if (std::strcmp(text, "Partly Cloudy") == 0) return "Parzialmente nuvoloso";
  if (std::strcmp(text, "Partly Cloudy Night") == 0) return "Notte parzialmente nuvolosa";
  if (std::strcmp(text, "Partly Lightning") == 0) return "Fulmini a tratti";
  if (std::strcmp(text, "Partly Rainy") == 0) return "Pioggia a tratti";
  if (std::strcmp(text, "Partly Snow And Rain") == 0) return "Neve e pioggia a tratti";
  if (std::strcmp(text, "Partly Snowy") == 0) return "Neve a tratti";
  if (std::strcmp(text, "Paused") == 0) return "In pausa";
  if (std::strcmp(text, "Pending") == 0) return "In attesa";
  if (std::strcmp(text, "PIN was not accepted") == 0) return "PIN non accettato";
  if (std::strcmp(text, "Play/Pause") == 0) return "Riproduci/Pausa";
  if (std::strcmp(text, "Playing") == 0) return "In riproduzione";
  if (std::strcmp(text, "Position") == 0) return "Posizione";
  if (std::strcmp(text, "Pouring") == 0) return "Pioggia intensa";
  if (std::strcmp(text, "Presence") == 0) return "Presenza";
  if (std::strcmp(text, "Previous") == 0) return "Precedente";
  if (std::strcmp(text, "Push") == 0) return "Premi";
  if (std::strcmp(text, "Rainy") == 0) return "Piovoso";
  if (std::strcmp(text, "Relay") == 0) return "Relè";
  if (std::strcmp(text, "Screen Dimmed") == 0) return "Schermo attenuato";
  if (std::strcmp(text, "Skip Next") == 0) return "Salta avanti";
  if (std::strcmp(text, "Skip Previous") == 0) return "Salta indietro";
  if (std::strcmp(text, "Snowy") == 0) return "Nevoso";
  if (std::strcmp(text, "Snowy And Rain") == 0) return "Neve e pioggia";
  if (std::strcmp(text, "Still") == 0) return "Fermo";
  if (std::strcmp(text, "Subpage") == 0) return "Sottopagina";
  if (std::strcmp(text, "Sunny") == 0) return "Soleggiato";
  if (std::strcmp(text, "Sunny Alert") == 0) return "Allerta sole";
  if (std::strcmp(text, "Sunset") == 0) return "Tramonto";
  if (std::strcmp(text, "Sunset Down") == 0) return "Tramonto giù";
  if (std::strcmp(text, "Sunset Up") == 0) return "Tramonto su";
  if (std::strcmp(text, "Swing") == 0) return "Oscillazione";
  if (std::strcmp(text, "Today") == 0) return "Oggi";
  if (std::strcmp(text, "Todo") == 0) return "Da fare";
  if (std::strcmp(text, "Toggle this device?") == 0) return "Commutare questo dispositivo?";
  if (std::strcmp(text, "Tomorrow") == 0) return "Domani";
  if (std::strcmp(text, "Track") == 0) return "Traccia";
  if (std::strcmp(text, "Triggered") == 0) return "Attivato";
  if (std::strcmp(text, "Turn off this device?") == 0) return "Spegnere questo dispositivo?";
  if (std::strcmp(text, "Turn on this device?") == 0) return "Accendere questo dispositivo?";
  if (std::strcmp(text, "Unavailable") == 0) return "Non disponibile";
  if (std::strcmp(text, "Unknown") == 0) return "Sconosciuto";
  if (std::strcmp(text, "Unlock") == 0) return "Sblocca";
  if (std::strcmp(text, "Unsupported") == 0) return "Non supportato";
  if (std::strcmp(text, "Version unknown") == 0) return "Versione sconosciuta";
  if (std::strcmp(text, "Waiting for Home Assistant") == 0) return "In attesa di Home Assistant";
  if (std::strcmp(text, "Weather") == 0) return "Meteo";
  if (std::strcmp(text, "Weekly") == 0) return "Settimanale";
  if (std::strcmp(text, "Window") == 0) return "Finestra";
  if (std::strcmp(text, "Window Closed") == 0) return "Finestra chiusa";
  if (std::strcmp(text, "Window Open") == 0) return "Finestra aperta";
  if (std::strcmp(text, "Windy") == 0) return "Ventoso";
  if (std::strcmp(text, "Windy And Cloudy") == 0) return "Ventoso e nuvoloso";
  if (std::strcmp(text, "World Clock") == 0) return "Orologio mondiale";
  if (std::strcmp(text, "Yes") == 0) return "Sì";
  return text;
}

inline const char *espcontrol_i18n(const char *text) {
  if (!text) return "";
  if (espcontrol_language_code() == "it") return espcontrol_i18n_it(text);
  return text;
}

inline std::string espcontrol_i18n(const std::string &text) {
  return std::string(espcontrol_i18n(text.c_str()));
}
